version: "3.11"
services:
  backend:
    build: .
    volumes:
      - .:/app
      - ./rosbag:/app/rosbag
    ports:
      - 8000:8000
      - 5678:5678
    image: backend:ros-annotator
    container_name: ros-annotator
    command: python manage.py runserver 0.0.0.0:8000
