version: "3.11"
services:
  backend:
    build: .
    volumes:
      - .:/app
      - ../../datas/rosbag-data:/app/datas/rosbag-data
      - ../../datas/booklist:/app/datas/booklist
      - ../../datas/annotation:/app/datas/annotation
      - ../../datas/processed:/app/processed_data
    ports:
      - 8000:8000 # port mapping for server
      - 5678:5678 # port mapping for debugger
    image: backend:ros-annotator
    container_name: ros-annotator
    command: python manage.py runserver 0.0.0.0:8000
